management:
  endpoints:
    web:
      exposure:
        include:
          - hawtio
          - jolokia

server:
  port: 2000

hawtio:
  authenticationEnabled: false

spring:
  activemq:
    broker-url: tcp://localhost:61616