spring:
  artemis:
    mode: embedded
    embedded:
      enabled: true
      queues: eventQueue
  jms:
    cache:
      session-cache-size: 5

management:
  endpoints:
    web:
      exposure:
        include:
          - hawtio
          - jolokia

server:
  port: 2000

hawtio:
  authenticationEnabled: false

application:
  events:
    auto-device-register: true
    batch-result-auto-send: true
  jms:
    queues:
      appQueue: eventQueue

logging:
  pattern:
    console: